"use client";

import { useState } from "react";

interface Draft {
  id: string;
  question: string;
  answer_suggestion: string;
  status: "Pending" | "Approved" | "Rejected";
  sources: Source[];
}

interface Source {
  url: string;
  score: number;
}

interface QuestionSectionProps {
  question: string;
  setQuestion: (val: string) => void;
  municipalityId: string;
  citizenEmail: string;
  setCitizenEmail: (val: string) => void;
}

const API_BASE =
  process.env.NEXT_PUBLIC_API_BASE || "http://localhost:3000";

export default function QuestionSection({
  question,
  setQuestion,
  municipalityId,
  citizenEmail,
  setCitizenEmail,
}: QuestionSectionProps) {
  const [asking, setAsking] = useState(false);
  const [submittingApproval, setSubmittingApproval] = useState(false);
  const [submittingReject, setSubmittingReject] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [language, setLanguage] = useState<"cs" | "en">("cs");

  // -----------------------------
  // TEXTS (Multilingual UI)
  // -----------------------------
  const texts = {
    cs: {
      placeholder: "Vložte dotaz občana...",
      emailPlaceholder: "Email občana (pro odeslání po schválení)",
      create: "Vytvořit návrh",
      generating: "Generuji návrh odpovědi...",
      title: "Návrh AI odpovědi",
      sources: "Zdroje:",
      approve: "Schválit odpověď",
      approving: "Schvaluji...",
      reject: "Zamítnout",
      rejecting: "Zamítám...",
      approvedMsg: "✓ Odpověď byla schválena a odeslána občanovi.",
      rejectedMsg: "✕ Návrh byl zamítnut.",
      error: "Chyba při zpracování dotazu.",
      footer:
        "Tento návrh odpovědi byl vygenerován pomocí AI a podléhá schválení odpovědnou osobou.",
      empty: "Vložte dotaz občana pro vytvoření návrhu odpovědi.",
    },
    en: {
      placeholder: "Enter citizen question...",
      emailPlaceholder: "Citizen email (for delivery after approval)",
      create: "Generate Draft",
      generating: "Generating draft response...",
      title: "AI Draft Reply",
      sources: "Sources:",
      approve: "Approve",
      approving: "Approving...",
      reject: "Reject",
      rejecting: "Rejecting...",
      approvedMsg: "✓ Reply approved and sent to citizen.",
      rejectedMsg: "✕ Draft rejected.",
      error: "Error while processing the request.",
      footer:
        "This response draft was generated by AI and requires approval by responsible authority.",
      empty: "Enter a citizen question to generate a draft reply.",
    },
  };

  const t = texts[language];

  // --------------------------------------------------
  // CREATE DRAFT
  // --------------------------------------------------
  const ask = async () => {
    if (!question.trim()) return;

    setAsking(true);
    setMessage(null);
    setDraft(null);

    try {
      const res = await fetch(`${API_BASE}/process-question`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          question,
          language, // send language to backend
          municipality_id: municipalityId.trim() || undefined,
          citizen_email: citizenEmail.trim() || undefined,
        }),
      });

      if (!res.ok) {
        let apiError = "Process-question failed";
        try {
          const errorBody = await res.json();
          apiError = errorBody?.error || apiError;
        } catch {
          // Keep generic fallback.
        }
        throw new Error(apiError);
      }

      const data = await res.json();

      const draftRes = await fetch(
        `${API_BASE}/draft/${data.draft_id}`
      );

      if (!draftRes.ok) {
        throw new Error("Draft fetch failed");
      }

      const draftData = await draftRes.json();

      setDraft(draftData);
      setQuestion("");
    } catch (err) {
      console.error(err);
      const msg = err instanceof Error ? err.message : t.error;
      setMessage(msg);
    }

    setAsking(false);
  };

  // --------------------------------------------------
  // APPROVE
  // --------------------------------------------------
  const approve = async () => {
    if (!draft) return;

    setSubmittingApproval(true);
    setMessage(null);

    try {
      const res = await fetch(
        `${API_BASE}/draft/${draft.id}/approve`,
        { method: "PUT" }
      );

      if (!res.ok) {
        let apiError = "Approve failed";
        try {
          const errorBody = await res.json();
          apiError = errorBody?.error || apiError;
        } catch {
          // Keep generic fallback.
        }
        throw new Error(apiError);
      }

      const updatedDraft = await res.json();
      setDraft(updatedDraft);
      setMessage(t.approvedMsg);
    } catch (err) {
      console.error(err);
      const msg = err instanceof Error ? err.message : t.error;
      setMessage(msg);
    } finally {
      setSubmittingApproval(false);
    }
  };

  // --------------------------------------------------
  // REJECT
  // --------------------------------------------------
  const reject = async () => {
    if (!draft) return;

    setSubmittingReject(true);
    setMessage(null);

    try {
      const res = await fetch(
        `${API_BASE}/draft/${draft.id}/reject`,
        { method: "PUT" }
      );

      if (!res.ok) {
        let apiError = "Reject failed";
        try {
          const errorBody = await res.json();
          apiError = errorBody?.error || apiError;
        } catch {
          // Keep generic fallback.
        }
        throw new Error(apiError);
      }

      const updatedDraft = await res.json();
      setDraft(updatedDraft);
      setMessage(t.rejectedMsg);
    } catch (err) {
      console.error(err);
      const msg = err instanceof Error ? err.message : t.error;
      setMessage(msg);
    } finally {
      setSubmittingReject(false);
    }
  };

  return (
    <div className="flex flex-col h-[80vh] bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      {/* Language Toggle */}
      <div className="flex justify-end p-3 border-b bg-gray-50">
        <div className="flex gap-2">
          <button
            onClick={() => setLanguage("cs")}
            className={`px-3 py-1 rounded-lg text-sm ${
              language === "cs"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-gray-700"
            }`}
          >
            🇨🇿 Česky
          </button>

          <button
            onClick={() => setLanguage("en")}
            className={`px-3 py-1 rounded-lg text-sm ${
              language === "en"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-gray-700"
            }`}
          >
            🇬🇧 English
          </button>
        </div>
      </div>

      {/* Draft Display Area */}
      <div className="flex-1 overflow-y-auto p-6">
        {!draft && !asking && (
          <div className="h-full flex flex-col items-center justify-center text-gray-400">
            <span className="text-4xl mb-2">🏛</span>
            <p>{t.empty}</p>
          </div>
        )}

        {asking && (
          <div className="text-gray-500 animate-pulse">
            {t.generating}
          </div>
        )}

        {draft && (
          <div className="space-y-4">
            <h2 className="text-xl font-bold text-black">
              {t.title}
            </h2>

            <p className="text-gray-800 whitespace-pre-wrap">
              {draft.answer_suggestion}
            </p>

            {draft.sources?.length > 0 && (
              <div className="text-sm mt-4">
                <p className="font-semibold text-gray-500 mb-2">
                  {t.sources}
                </p>
                <div className="flex flex-wrap gap-2">
                  {draft.sources.map((s, i) => (
                    <a
                      key={i}
                      href={s.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="bg-gray-100 px-2 py-1 rounded border border-gray-200 hover:bg-gray-200 truncate max-w-[200px]"
                    >
                      {s.url}
                    </a>
                  ))}
                </div>
              </div>
            )}

            {draft.status === "Pending" && (
              <div className="flex gap-4 mt-6">
                <button
                  onClick={approve}
                  disabled={submittingApproval || submittingReject}
                  className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 disabled:bg-gray-300"
                >
                  {submittingApproval ? t.approving : t.approve}
                </button>

                <button
                  onClick={reject}
                  disabled={submittingApproval || submittingReject}
                  className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 disabled:bg-gray-300"
                >
                  {submittingReject ? t.rejecting : t.reject}
                </button>
              </div>
            )}

            {draft.status !== "Pending" && (
              <div className="text-sm text-gray-500 mt-4">
                Status: {draft.status}
              </div>
            )}
          </div>
        )}

        {message && (
          <div className="mt-4 text-sm font-medium text-blue-600">
            {message}
          </div>
        )}
      </div>

      {/* Input Bar */}
      <div className="p-4 border-t bg-gray-50">
        <div className="max-w-3xl mx-auto flex gap-2">
          <div className="w-full space-y-2">
            <input
              type="email"
              placeholder={t.emailPlaceholder}
              value={citizenEmail}
              onChange={(e) => setCitizenEmail(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-black"
            />
            <textarea
              rows={1}
              placeholder={t.placeholder}
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none resize-none text-black"
            />
          </div>

          <button
            onClick={ask}
            disabled={asking || !question.trim() || !citizenEmail.trim()}
            className="bg-blue-600 text-white px-4 py-2 rounded-xl hover:bg-blue-700 disabled:bg-gray-300"
          >
            {t.create}
          </button>
        </div>

        <p className="text-[10px] text-center mt-2 text-gray-400">
          {t.footer}
        </p>
      </div>
    </div>
  );
}
